name: Publish Package to npmjs

on:
  release:
    types: [published]
permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "25.x"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install node-gyp
        run: pnpm install --global node-gyp

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm build

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Run tests
        run: pnpm test

      - name: Publish to npmjs
        run: pnpm publish --access public
