name: linting and tests

on:
  push:
    branches:
      - main
    paths:
      [
        "**.js",
        "**.ts",
        "**.jsx",
        "**.tsx",
        "**.json",
        "**.md",
        "**.yml",
        "**.yaml",
      ]
  pull_request:
    paths:
      [
        "**.js",
        "**.ts",
        "**.jsx",
        "**.tsx",
        "**.json",
        "**.md",
        "**.yml",
        "**.yaml",
      ]

jobs:
  format:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "25.x"
          cache: "pnpm"

      - name: Install node-gyp
        run: pnpm install --global node-gyp

      - name: Install dependencies
        run: pnpm install

      - name: Run biome check + tests
        run: pnpm test
